default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: road_surface_analyzer_development  #name of your database
  username: postgres #username you provided when installing postgresql. By default its postgres(if you did not provide any)
  password: postgres  #password you provided when installing postgresql

test:
  <<: *default
  database: road_surface_analyzer_test    #name of your database
  username: postgres #username you provided when installing postgresql. By default its postgres(if you did not provide any)
  password: postgres  #password you provided when installing postgresql

production:
  <<: *default
  database: <%= ENV["DATABASE_URL"] %>