default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: road_surface_analyzer_development  #name of your database

test:
  <<: *default
  database: road_surface_analyzer_test    #name of your database

production:
  <<: *default
  database: <%= ENV["DATABASE_URL"] %>