---
name: activesupport
version: '7.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: c604d278dd6c14a1bb6cf0c0051af643b268a981
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
